kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "python-sample" 
spec:
  runPolicy: "Serial" 
  triggers: 
    -
      type: "ImageChange"
  source: 
    git:
      uri: "https://github.com/chriskretler/pinger"
  strategy: 
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "python:2.7"
  output: 
    to:
      kind: "ImageStreamTag"
      name: "pinger:latest"
