apiVersion: v1
kind: Pod
metadata:
  name: pinger-pod-4
spec:
  containers:
  - name: pod
    image: 172.30.183.221:5000/chris-sandbox/pinger
    command: ["python", "pinger.py"]
    restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: os-node4.dsc.umich.edu